spring.application.name=GestionBiblioteca
server.port=8085
spring.datasource.url=jdbc:mysql://localhost:3306/biblioteca_app
#spring.datasource.url=jdbc:mysql://172.16.8.208:3306/notes
spring.datasource.username=root
spring.datasource.password=
#spring.datasource.username=root
#spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
jwt.secret=mi-secreto-super-seguro-y-largo-para-jwt-biblioteca-2025
jwt.expiration=86400000
